//************ sym.h **************
#define symSYMMAX         500
#define symEOF             0
#define symerror           1
#define symIDENTIFIER      2
#define symNUMBER          3
#define symPLUS            4
#define symMINUS           5
#define symMUL             6
#define symDIV             7
#define symEQ              8
#define symNEQ             9
#define symLESS           10
#define symLEQ            11
#define symGREATER        12
#define symGEQ            13
#define symLPAREN         14
#define symRPAREN         15
#define symCOMMA          16
#define symSEMI           17
#define symPERIOD         18
#define symBECOMES        19
#define symBEGIN          20
#define symEND            21
#define symIF             22
#define symTHEN           23
#define symWHILE          24
#define symDO             25
#define symREAD           26
#define symWRITE          27
#define symIDENTIFIERLIST 28
#define symCALL           29
// #define symCONST          30
#define symVAR            31
#define symPROCEDURE      32
#define symPROGRAM        33
#define symSTRING         34
#define symELSE           35
#define symLMOD           36
// storage-class-specifier
#define symSCSBEGIN       37 
#define symAUTO           38
#define symREGISTER       39 
#define symSTATIC         40
#define symEXTERN         41
#define symTYPEDEF        42
#define symSCSEND         43
// type-qualifier
#define symTQBEGIN        45
#define symCONST          46
#define symVOLATILE       47
#define symTQEND          48
// storage-class-specifier
#define symTSBEGIN        50
#define symVOID           51
#define symCHAR           52
#define symSHORT          53
#define symINT            54
#define symLONG           55
#define symFLOAT          56
#define symDOUBLE         57
#define symSIGNED         58
#define symUNSIGNED       59
#define symTSEND          65
// C++ Define symbol
#define symLCURLY         70
#define symRCURLY         71